# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prod_1 <- function(M, m) {
    .Call(`_ulgee_prod_1`, M, m)
}

prod_2 <- function(R, sigma, D) {
    .Call(`_ulgee_prod_2`, R, sigma, D)
}

prod_3 <- function(X, W) {
    .Call(`_ulgee_prod_3`, X, W)
}

prod_4 <- function(S1, s2) {
    .Call(`_ulgee_prod_4`, S1, s2)
}

prod_5 <- function(S1, S3) {
    .Call(`_ulgee_prod_5`, S1, S3)
}
